/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as FootagesIndexRouteImport } from './routes/footages/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as FootagesEditFootageRouteImport } from './routes/footages/$EditFootage'
import { Route as CustomersNewRouteImport } from './routes/customers/new'
import { Route as CustomersIdRouteImport } from './routes/customers/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const FootagesIndexRoute = FootagesIndexRouteImport.update({
  id: '/footages/',
  path: '/footages/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const FootagesEditFootageRoute = FootagesEditFootageRouteImport.update({
  id: '/footages/$EditFootage',
  path: '/footages/$EditFootage',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/footages/$EditFootage': typeof FootagesEditFootageRoute
  '/customers/': typeof CustomersIndexRoute
  '/files/': typeof FilesIndexRoute
  '/footages/': typeof FootagesIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/footages/$EditFootage': typeof FootagesEditFootageRoute
  '/customers': typeof CustomersIndexRoute
  '/files': typeof FilesIndexRoute
  '/footages': typeof FootagesIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers/$id': typeof CustomersIdRoute
  '/customers/new': typeof CustomersNewRoute
  '/footages/$EditFootage': typeof FootagesEditFootageRoute
  '/customers/': typeof CustomersIndexRoute
  '/files/': typeof FilesIndexRoute
  '/footages/': typeof FootagesIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/footages/$EditFootage'
    | '/customers/'
    | '/files/'
    | '/footages/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/footages/$EditFootage'
    | '/customers'
    | '/files'
    | '/footages'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/customers/$id'
    | '/customers/new'
    | '/footages/$EditFootage'
    | '/customers/'
    | '/files/'
    | '/footages/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersIdRoute: typeof CustomersIdRoute
  CustomersNewRoute: typeof CustomersNewRoute
  FootagesEditFootageRoute: typeof FootagesEditFootageRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  FilesIndexRoute: typeof FilesIndexRoute
  FootagesIndexRoute: typeof FootagesIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footages/': {
      id: '/footages/'
      path: '/footages'
      fullPath: '/footages/'
      preLoaderRoute: typeof FootagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footages/$EditFootage': {
      id: '/footages/$EditFootage'
      path: '/footages/$EditFootage'
      fullPath: '/footages/$EditFootage'
      preLoaderRoute: typeof FootagesEditFootageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersIdRoute: CustomersIdRoute,
  CustomersNewRoute: CustomersNewRoute,
  FootagesEditFootageRoute: FootagesEditFootageRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  FilesIndexRoute: FilesIndexRoute,
  FootagesIndexRoute: FootagesIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
